name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Update the system and install Docker if not installed
          sudo apt update
          sudo apt install -y docker.io git

          # Clone the repository (or pull latest changes)
          if [ ! -d "app" ]; then
            git clone https://github.com/nidheeshnle/NodeJs-app.git app
          else
            cd app
            git pull origin main
          fi

          cd app

          # Build and run the Docker container
          sudo docker stop node-app || true
          sudo docker rm node-app || true
          sudo docker build -t node-app .
          sudo docker run -d -p 80:3000 --name node-app node-app
